"""Initial

Revision ID: 8e067ebf3f60
Revises: 
Create Date: 2023-12-06 21:59:59.704178

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8e067ebf3f60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'marketing_dealer',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'marketing_product',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('article', sa.String(), nullable=False),
        sa.Column('ean_13', sa.BigInteger(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('cost', sa.Float(), nullable=True),
        sa.Column('recommended_price', sa.Float(), nullable=True),
        sa.Column('category_id', sa.Integer(), nullable=True),
        sa.Column('ozon_name', sa.String(), nullable=True),
        sa.Column('name_1c', sa.String(), nullable=True),
        sa.Column('wb_name', sa.String(), nullable=True),
        sa.Column('ozon_article', sa.Integer(), nullable=True),
        sa.Column('wb_article', sa.Integer(), nullable=True),
        sa.Column('ym_article', sa.String(), nullable=True),
        sa.Column('wb_article_td', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('article'),
    )
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column('role', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username'),
    )
    op.create_table(
        'marketing_productdealerkey',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('key', sa.Integer(), nullable=False),
        sa.Column('dealer_id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['dealer_id'],
            ['marketing_dealer.id'],
        ),
        sa.ForeignKeyConstraint(
            ['product_id'],
            ['marketing_product.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('key'),
    )
    op.create_table(
        'marketing_dealerprice',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('product_key', sa.Integer(), nullable=True),
        sa.Column('price', sa.Float(), nullable=True),
        sa.Column('product_url', sa.String(), nullable=True),
        sa.Column('product_name', sa.String(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('dealer_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['dealer_id'],
            ['marketing_dealer.id'],
        ),
        sa.ForeignKeyConstraint(
            ['product_key'],
            ['marketing_productdealerkey.key'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'marketing_statistics',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('parsed_data_id', sa.Integer(), nullable=False),
        sa.Column('skipped', sa.Boolean(), nullable=False),
        sa.Column('successfull', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['parsed_data_id'],
            ['marketing_dealerprice.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('parsed_data_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marketing_statistics')
    op.drop_table('marketing_dealerprice')
    op.drop_table('marketing_productdealerkey')
    op.drop_table('users')
    op.drop_table('marketing_product')
    op.drop_table('marketing_dealer')
    # ### end Alembic commands ###
