version: '3'

volumes:
  pg_data:

services:
  db:
    image: postgres:15
    env_file: server.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    env_file: server.env
    command: ["bash", "./app/docker/app.sh"]
    volumes:
      - ./app/data:/root/app/app/data

  gateway:
    build: 
      context: ./gateway/
      dockerfile: Dockerfile
    ports:
      - 8000:80
