version: '3'

volumes:
  pg_data:

services:
  db:
    image: postgres:15
    env_file: deploy.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    depends_on:
      - db
    build:
      context: .
    env_file: deploy.env
    command: ["bash", "./app/docker/app.sh"]

  gateway:
    build: ../Point-return-gateway/
    ports:
      - 8000:80
