version: '3'

volumes:
  pg_data:

services:
  db:
    image: postgres:13.10
    env_file: deploy.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    depends_on:
      - db
    image: starkiller2000/point-backend
    env_file: deploy.env
    command: ["bash", "./app/docker/app.sh"]

  gateway:
    image: starkiller2000/point-gateway
    ports:
      - 8000:80
